### ISSUE TITLE
nom installs an old version of the code

### ISSUE THREAD

**Issue by igt-peterrussell** [jbree/persistent-counter#1]
the version installed from npm is not the latest version in GitHub.
This causes an error at runtime - you can see this error if you run your example from here:
https://npm.runkit.com/persistent-counter

**Comment by jbree** [comment]
I don't think that's the issue. I'm using typescript and the way it would require you to import it like so:
`var PersistentCounter = require('persistent-counter').default`.

That being said, there are some serious issues with this package and it should not be used. It has been deprecated on npm now to indicate this fact.
